services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  # Redis (necessário para o Sidekiq)
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  # Aplicação Rails (Web)
  web:
    build: .
    platform: linux/amd64
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  # Compilador Automático do Tailwind (Assiste alterações nas views e recompila o CSS)
  css:
    build: .
    platform: linux/amd64
    command: bundle exec rails tailwindcss:watch
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    depends_on:
      - web

  # Worker do Sidekiq
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: